import { AccountsTemplates } from 'meteor/useraccounts:core'

// User accounts configuration
// https://github.com/meteor-useraccounts/core/blob/master/Guide.md
/* These settings may only apply to the full-page template generated by the useraccounts package, and not the
    bootstrap dropdown I'm using */
AccountsTemplates.configure({
  // TODO Not seeing these in the nav dropdown login...

  // Privacy Policy and Terms of Use
  // privacy/tos are working routes & have the appropriate templates (dummy text)
  privacyUrl: 'privacy',
  termsUrl: 'terms-of-service'

  // Hooks
  /*
  onLogoutHook: myLogoutFunc,
  onSubmitHook: mySubmitFunc,
  preSignUpHook: myPreSubmitFunc,
  postSignUpHook: myPostSubmitFunc,
  */
})
